#!/usr/bin/env python3
"""
Blender → Sionna RT 场景 XML 生成器

将 Blender 导出的 PLY 文件目录转换为 Sionna RT 兼容的 Mitsuba XML 场景文件。

用法:
    python generate_scene_xml.py --ply_dir ./meshes --material_map ./materials.json \\
                                  --output ./scene.xml --scene_name "my_drone_scene"

material_map JSON 格式:
    {
        "mesh_name_1": {"material": "metal", "thickness": 0.05},
        "mesh_name_2": {"material": "concrete", "thickness": 0.1}
    }
"""

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Dict, Optional

# ── ITU 无线电材料映射 ────────────────────────────────────────────
# 完整列表（与 sionna.rt.radio_materials.itu 对齐）
ITU_MATERIALS = {
    "metal", "wood", "concrete", "brick", "glass",
    "plasterboard", "marble", "ceiling_board", "fiber_glass",
    "tiles", "floorboard",
    "very_dry_ground", "medium_dry_ground", "wet_ground",
}

XML_TEMPLATE = """<scene version="2.1.0">

<!-- ============================================================
     Auto-generated by generate_scene_xml.py
     Scene: {scene_name}
     ============================================================ -->

<!-- Materials -->
{bsdf_block}
<!-- Shapes -->
{shapes_block}
</scene>
"""

BSDF_TEMPLATE = """        <bsdf type="itu-radio-material" id="{mat_id}">
            <string name="type" value="{mat_type}"/>
            <float name="thickness" value="{thickness}"/>
        </bsdf>"""

SHAPE_TEMPLATE = """        <shape type="ply" id="mesh-{mesh_id}">
            <string name="filename" value="meshes/{filename}"/>
            <boolean name="face_normals" value="true"/>
            <ref id="{mat_id}" name="bsdf"/>
        </shape>"""


def load_material_map(json_path: str) -> Dict[str, dict]:
    """加载材质映射 JSON 文件"""
    with open(json_path, "r") as f:
        material_map = json.load(f)

    for mesh_name, mat_info in material_map.items():
        if "material" not in mat_info:
            raise ValueError(f"网格 '{mesh_name}' 缺少 'material' 字段")
        mat = mat_info["material"]
        if mat not in ITU_MATERIALS:
            print(f"警告: '{mat}' 不是标准 ITU 材料，支持的列表: {sorted(ITU_MATERIALS)}",
                  file=sys.stderr)
    return material_map


def find_ply_files(ply_dir: str) -> list[str]:
    """在目录中找到所有 .ply 文件"""
    ply_files = sorted(Path(ply_dir).glob("*.ply"))
    if not ply_files:
        raise FileNotFoundError(f"在 '{ply_dir}' 中未找到 .ply 文件")
    return [p.name for p in ply_files]


def generate_xml(
    ply_dir: str,
    material_map_path: str,
    scene_name: str = "custom_scene",
    default_material: str = "metal",
    default_thickness: float = 0.1,
) -> str:
    """
    生成 Mitsuba XML 场景文件字符串。

    Args:
        ply_dir: PLY 文件所在目录
        material_map_path: 材质映射 JSON 路径
        scene_name: 场景名称
        default_material: 未在映射中找到的网格的默认材质
        default_thickness: 默认材质厚度 [m]
    """
    # 加载材质映射
    material_map = load_material_map(material_map_path) if material_map_path else {}
    ply_files = find_ply_files(ply_dir)

    # 收集所有使用的材料
    unique_materials: Dict[str, dict] = {}
    for ply_file in ply_files:
        mesh_name = Path(ply_file).stem
        mat_info = material_map.get(mesh_name, {"material": default_material, "thickness": default_thickness})
        mat_type = mat_info["material"]
        thickness = mat_info.get("thickness", default_thickness)
        # 每个不同的 (material, thickness) 组合一个 bsdf 定义
        key = f"{mat_type}_{thickness}"
        if key not in unique_materials:
            unique_materials[key] = {"type": mat_type, "thickness": thickness}

    # 构建 BSDF 块
    bsdf_lines = []
    for mat_id, mat_info in sorted(unique_materials.items()):
        bsdf_lines.append(BSDF_TEMPLATE.format(
            mat_id=mat_id,
            mat_type=mat_info["type"],
            thickness=mat_info["thickness"],
        ))
    bsdf_block = "\n".join(bsdf_lines)

    # 构建 Shapes 块
    shape_lines = []
    for ply_file in ply_files:
        mesh_name = Path(ply_file).stem
        mat_info = material_map.get(mesh_name, {"material": default_material, "thickness": default_thickness})
        mat_key = f"{mat_info['material']}_{mat_info.get('thickness', default_thickness)}"
        shape_lines.append(SHAPE_TEMPLATE.format(
            mesh_id=mesh_name,
            filename=ply_file,
            mat_id=mat_key,
        ))
    shapes_block = "\n".join(shape_lines)

    return XML_TEMPLATE.format(
        scene_name=scene_name,
        bsdf_block=bsdf_block,
        shapes_block=shapes_block,
    )


def main():
    parser = argparse.ArgumentParser(
        description="将 Blender 导出 PLY → Sionna RT Mitsuba XML 场景"
    )
    parser.add_argument("--ply_dir", required=True, help="PLY 网格文件目录")
    parser.add_argument("--material_map", default=None, help="材质映射 JSON 文件路径")
    parser.add_argument("--output", required=True, help="输出 XML 文件路径")
    parser.add_argument("--scene_name", default="custom_scene", help="场景名称")
    parser.add_argument("--default_material", default="metal", help="默认材质（未在映射中的）")
    parser.add_argument("--default_thickness", type=float, default=0.1, help="默认材质厚度 [m]")

    args = parser.parse_args()

    xml = generate_xml(
        ply_dir=args.ply_dir,
        material_map_path=args.material_map,
        scene_name=args.scene_name,
        default_material=args.default_material,
        default_thickness=args.default_thickness,
    )

    # 确保输出目录存在
    os.makedirs(os.path.dirname(args.output) or ".", exist_ok=True)

    with open(args.output, "w") as f:
        f.write(xml)

    ply_count = len(find_ply_files(args.ply_dir))
    print(f"生成完成: {args.output}")
    print(f"  PLY 文件: {ply_count} 个")
    print(f"  场景名称: {args.scene_name}")
    print(f"  下一步: scene = load_scene('{args.output}')")

    # 同时输出推荐的目录结构
    print(f"\n推荐的目录结构:")
    print(f"  {os.path.dirname(args.output) or '.'}/")
    print(f"  ├── {os.path.basename(args.output)}     ← 场景 XML（已生成）")
    print(f"  └── meshes/                ← 将 PLY 文件放入此目录")


if __name__ == "__main__":
    main()
