#!/usr/bin/env python3
"""RT-generated single-rotor micro-Doppler vs standard Doppler comparison.

This script deliberately does *not* use ``MicroDopplerModulator`` to generate
signals. Instead, it repeatedly updates point-scatterer positions inside a
Sionna RT scene, runs ``PathSolver`` at every snapshot, and reconstructs the
complex baseband signal from the RT-generated CIR coefficients.

Two cases are compared:

1. Standard Doppler
   A single point target moves linearly relative to a fixed radar.

2. Single-rotor Micro-Doppler
   A body point plus one rotor with N blade-tip point scatterers. By default,
   N=2, i.e., a two-blade single propeller / micro-helicopter-like model.
   Each snapshot is generated by Sionna RT at the current blade-tip positions,
   so the phase modulation comes from RT path geometry.

Important modeling note:
- This is still a point-scatterer RT approximation. Each blade tip is modeled
  as an active point transmitter and the radar is a receiver. Therefore, the
  signal is a one-way RT CIR-based signal, not a full monostatic radar
  Tx -> blade reflection -> Rx round-trip model.
"""

from __future__ import annotations

import argparse
import time
from dataclasses import dataclass
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
from scipy.constants import c as SPEED_OF_LIGHT
from scipy.signal import spectrogram, windows

import sionna
from sionna.rt import PathSolver, PlanarArray, Receiver, Transmitter, load_scene


OUT_DIR = Path(__file__).resolve().parent.parent / "figures"
OUT_DIR.mkdir(exist_ok=True)


@dataclass(frozen=True)
class RtCaseConfig:
    carrier_freq: float = 28e9
    fs_snapshot: float = 1000.0
    n_snapshots: int = 512
    cir_sampling_frequency: float = 122.88e6

    # Radar and target geometry
    radar_position: tuple[float, float, float] = (-20.0, 0.0, 3.0)
    body_center: tuple[float, float, float] = (0.0, 0.0, 3.0)

    # Standard Doppler case
    standard_speed: float = 2.0

    # Single-rotor micro-Doppler case
    blade_radius: float = 0.02
    rotation_freq: float = 20.0
    n_blades_per_rotor: int = 2
    rotor_offset: tuple[float, float, float] = (0.0, 0.0, 0.0)
    rotor_initial_phase: float = 0.0

    # Relative scatterer weights used when coherently summing RT CIRs
    body_weight: float = 1.0
    blade_weight: float = 0.18

    # RT settings
    max_depth: int = 0
    diffuse_reflection: bool = False
    specular_reflection: bool = True

    @property
    def dt(self) -> float:
        return 1.0 / self.fs_snapshot

    @property
    def t_vec(self) -> np.ndarray:
        return np.arange(self.n_snapshots, dtype=np.float64) * self.dt

    @property
    def wavelength(self) -> float:
        return SPEED_OF_LIGHT / self.carrier_freq

    @property
    def nyquist(self) -> float:
        return 0.5 * self.fs_snapshot

    @property
    def one_way_beta_max(self) -> float:
        # For one-way active-point TX -> RX geometry: beta ~= 2*pi*R/lambda.
        # For monostatic radar round-trip, this would be roughly doubled.
        return 2.0 * np.pi * self.blade_radius / self.wavelength

    @property
    def one_way_peak_micro_doppler(self) -> float:
        return self.one_way_beta_max * self.rotation_freq


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate single-rotor micro-Doppler vs standard Doppler using Sionna RT snapshots."
    )
    parser.add_argument("--scene", choices=["floor_wall", "etoile"], default="floor_wall")
    parser.add_argument(
        "--output",
        default=str(OUT_DIR / "single_rotor_micro_doppler_vs_standard_doppler.png"),
    )
    parser.add_argument("--snapshots", type=int, default=512)
    parser.add_argument("--fs", type=float, default=1000.0, help="Snapshot rate [Hz].")
    parser.add_argument("--fc", type=float, default=28e9, help="Carrier frequency [Hz].")
    parser.add_argument("--max-depth", type=int, default=0)
    parser.add_argument("--diffuse", action="store_true")
    parser.add_argument("--standard-speed", type=float, default=2.0, help="Linear target speed [m/s].")
    parser.add_argument("--blade-radius", type=float, default=0.02, help="Blade-tip radius [m].")
    parser.add_argument("--rotation-freq", type=float, default=20.0, help="Rotor rotation frequency [Hz].")
    parser.add_argument("--n-blades", type=int, default=2, help="Number of blades on the single rotor.")
    parser.add_argument("--rotor-offset-x", type=float, default=0.0, help="Rotor-center x offset from body center [m].")
    parser.add_argument("--rotor-offset-y", type=float, default=0.0, help="Rotor-center y offset from body center [m].")
    parser.add_argument("--rotor-offset-z", type=float, default=0.0, help="Rotor-center z offset from body center [m].")
    parser.add_argument("--rotor-phase", type=float, default=0.0, help="Initial rotor phase [rad].")
    parser.add_argument("--body-weight", type=float, default=1.0, help="Relative body scatterer weight.")
    parser.add_argument("--blade-weight", type=float, default=0.18, help="Relative weight of each blade-tip scatterer.")
    return parser.parse_args()


def load_rt_scene(scene_name: str, carrier_freq: float):
    if scene_name == "etoile":
        scene = load_scene(sionna.rt.scene.etoile)
    else:
        scene = load_scene(sionna.rt.scene.floor_wall)

    scene.frequency = carrier_freq
    scene.tx_array = PlanarArray(
        num_rows=1,
        num_cols=1,
        vertical_spacing=0.5,
        horizontal_spacing=0.5,
        pattern="iso",
        polarization="V",
    )
    scene.rx_array = PlanarArray(
        num_rows=1,
        num_cols=1,
        vertical_spacing=0.5,
        horizontal_spacing=0.5,
        pattern="iso",
        polarization="V",
    )
    return scene


def run_solver(scene, solver: PathSolver, cfg: RtCaseConfig):
    paths = solver(
        scene,
        max_depth=cfg.max_depth,
        los=True,
        specular_reflection=cfg.specular_reflection,
        diffuse_reflection=cfg.diffuse_reflection,
        diffraction=False,
        edge_diffraction=False,
        refraction=False,
        synthetic_array=False,
    )
    a, tau = paths.cir(
        sampling_frequency=cfg.cir_sampling_frequency,
        normalize_delays=False,
        out_type="numpy",
    )
    return np.asarray(a, dtype=np.complex128), np.asarray(tau, dtype=np.float64)


def sum_all_paths_by_tx(a: np.ndarray, tx_weights: np.ndarray) -> complex:
    """Reconstruct one complex sample from a SISO multi-TX CIR tensor.

    Expected Sionna shape used by this script:
    [num_rx, num_time_steps, num_tx, num_tx_ant, num_paths, num_rx_ant]
    """
    if a.ndim != 6:
        raise ValueError(f"Expected 6-D CIR coefficient tensor, got shape {a.shape}")

    # Sum all paths for every TX, then coherently combine TXs with weights.
    tx_path_coeffs = np.sum(a[0, 0, :, 0, :, 0], axis=-1)  # [num_tx]
    n = min(len(tx_path_coeffs), len(tx_weights))
    return np.sum(tx_weights[:n] * tx_path_coeffs[:n])


def setup_standard_scene(scene_name: str, cfg: RtCaseConfig):
    scene = load_rt_scene(scene_name, cfg.carrier_freq)
    scene.add(
        Transmitter(
            name="target",
            position=list(cfg.body_center),
            orientation=[0, 0, 0],
            power_dbm=0.0,
        )
    )
    scene.add(
        Receiver(
            name="radar",
            position=list(cfg.radar_position),
            orientation=[0, 0, 0],
        )
    )
    return scene


def setup_micro_scene(scene_name: str, cfg: RtCaseConfig):
    """Create one body point and one single rotor with N blade-tip point TXs."""
    scene = load_rt_scene(scene_name, cfg.carrier_freq)
    scene.add(
        Receiver(
            name="radar",
            position=list(cfg.radar_position),
            orientation=[0, 0, 0],
        )
    )
    scene.add(
        Transmitter(
            name="body",
            position=list(cfg.body_center),
            orientation=[0, 0, 0],
            power_dbm=0.0,
        )
    )

    for idx in range(cfg.n_blades_per_rotor):
        scene.add(
            Transmitter(
                name=f"blade_{idx}",
                position=list(cfg.body_center),
                orientation=[0, 0, 0],
                power_dbm=0.0,
            )
        )
    return scene


def single_rotor_blade_positions(cfg: RtCaseConfig, t: float) -> np.ndarray:
    """Return positions of blade-tip point scatterers for a single rotor.

    The rotor center is body_center + rotor_offset. Blades are uniformly spaced
    in phase. For the default N=2, the two blade tips are separated by pi rad.
    """
    center = np.asarray(cfg.body_center, dtype=np.float64)
    rotor_center = center + np.asarray(cfg.rotor_offset, dtype=np.float64)
    omega = 2.0 * np.pi * cfg.rotation_freq

    positions = []
    for blade_idx in range(cfg.n_blades_per_rotor):
        blade_phase = 2.0 * np.pi * blade_idx / cfg.n_blades_per_rotor
        angle = omega * t + cfg.rotor_initial_phase + blade_phase
        positions.append(
            rotor_center
            + np.asarray(
                [
                    cfg.blade_radius * np.cos(angle),
                    cfg.blade_radius * np.sin(angle),
                    0.0,
                ],
                dtype=np.float64,
            )
        )
    return np.asarray(positions, dtype=np.float64)


def simulate_standard_rt(scene_name: str, cfg: RtCaseConfig) -> dict:
    scene = setup_standard_scene(scene_name, cfg)
    solver = PathSolver()
    signal = np.zeros(cfg.n_snapshots, dtype=np.complex128)
    positions = np.zeros((cfg.n_snapshots, 3), dtype=np.float64)
    path_counts = np.zeros(cfg.n_snapshots, dtype=np.int32)

    print("\n[1/2] RT standard Doppler snapshots")
    start = time.perf_counter()
    for i, t in enumerate(cfg.t_vec):
        pos = np.asarray(cfg.body_center, dtype=np.float64) + np.asarray(
            [cfg.standard_speed * t, 0.0, 0.0], dtype=np.float64
        )
        scene.get("target").position = pos.tolist()
        a, _ = run_solver(scene, solver, cfg)
        signal[i] = sum_all_paths_by_tx(a, np.asarray([1.0], dtype=np.float64))
        positions[i] = pos
        path_counts[i] = a.shape[4]
        if (i + 1) % max(1, cfg.n_snapshots // 4) == 0:
            print(f"  standard {i + 1:4d}/{cfg.n_snapshots} snapshots")

    print(f"  standard done in {time.perf_counter() - start:.1f}s")
    return {"signal": signal, "positions": positions, "path_counts": path_counts}


def simulate_micro_rt(scene_name: str, cfg: RtCaseConfig) -> dict:
    scene = setup_micro_scene(scene_name, cfg)
    solver = PathSolver()
    signal = np.zeros(cfg.n_snapshots, dtype=np.complex128)
    body_positions = np.zeros((cfg.n_snapshots, 3), dtype=np.float64)
    first_blade_positions = np.zeros((cfg.n_snapshots, 3), dtype=np.float64)
    rotor_center_positions = np.zeros((cfg.n_snapshots, 3), dtype=np.float64)
    path_counts = np.zeros(cfg.n_snapshots, dtype=np.int32)

    weights = np.asarray(
        [cfg.body_weight] + [cfg.blade_weight] * cfg.n_blades_per_rotor,
        dtype=np.float64,
    )

    print("\n[2/2] RT single-rotor micro-Doppler snapshots")
    start = time.perf_counter()
    for i, t in enumerate(cfg.t_vec):
        body_pos = np.asarray(cfg.body_center, dtype=np.float64)
        rotor_center = body_pos + np.asarray(cfg.rotor_offset, dtype=np.float64)
        blade_positions = single_rotor_blade_positions(cfg, float(t))

        scene.get("body").position = body_pos.tolist()
        for blade_idx, blade_pos in enumerate(blade_positions):
            scene.get(f"blade_{blade_idx}").position = blade_pos.tolist()

        a, _ = run_solver(scene, solver, cfg)
        signal[i] = sum_all_paths_by_tx(a, weights)

        body_positions[i] = body_pos
        rotor_center_positions[i] = rotor_center
        first_blade_positions[i] = blade_positions[0]
        path_counts[i] = a.shape[4]

        if (i + 1) % max(1, cfg.n_snapshots // 4) == 0:
            print(f"  single-rotor {i + 1:4d}/{cfg.n_snapshots} snapshots")

    print(f"  single-rotor micro done in {time.perf_counter() - start:.1f}s")
    return {
        "signal": signal,
        "body_positions": body_positions,
        "rotor_center_positions": rotor_center_positions,
        "first_blade_positions": first_blade_positions,
        "path_counts": path_counts,
    }


def normalise_signal(signal: np.ndarray) -> np.ndarray:
    rms = np.sqrt(np.mean(np.abs(signal) ** 2))
    return signal / max(rms, 1e-12)


def instantaneous_frequency(signal: np.ndarray, fs: float) -> np.ndarray:
    phase = np.unwrap(np.angle(signal))
    return np.gradient(phase, 1.0 / fs) / (2.0 * np.pi)


def compute_spectrogram(signal: np.ndarray, cfg: RtCaseConfig):
    n_win = min(128, cfg.n_snapshots // 2)
    n_win = max(32, n_win)
    n_overlap = int(n_win * 0.875)
    _, _, z = spectrogram(
        signal,
        fs=cfg.fs_snapshot,
        window=windows.hann(n_win),
        nperseg=n_win,
        noverlap=n_overlap,
        mode="complex",
        return_onesided=False,
    )
    freq = np.fft.fftshift(np.fft.fftfreq(n_win, 1 / cfg.fs_snapshot))
    z = np.fft.fftshift(z, axes=0)
    power_db = 20 * np.log10(np.abs(z) + 1e-12)
    power_db -= np.max(power_db)
    hop = n_win - n_overlap
    t_spec = (np.arange(z.shape[1]) * hop + n_win / 2) / cfg.fs_snapshot
    return freq, t_spec, power_db


def plot_results(
    standard: dict,
    micro: dict,
    cfg: RtCaseConfig,
    scene_name: str,
    output_path: Path,
) -> None:
    t = cfg.t_vec
    standard_signal = normalise_signal(standard["signal"])
    micro_signal = normalise_signal(micro["signal"])

    f_std, ts_std, s_std = compute_spectrogram(standard_signal, cfg)
    f_micro, ts_micro, s_micro = compute_spectrogram(micro_signal, cfg)
    fi_std = instantaneous_frequency(standard_signal, cfg.fs_snapshot)
    fi_micro = instantaneous_frequency(micro_signal, cfg.fs_snapshot)

    fig = plt.figure(figsize=(14, 9))
    fig.suptitle(
        "RT-generated Single-Rotor Micro-Doppler vs Standard Doppler\n"
        f"Sionna RT scene={scene_name}, fc={cfg.carrier_freq/1e9:.1f} GHz, "
        f"fs={cfg.fs_snapshot:.0f} Hz, N={cfg.n_snapshots}, max_depth={cfg.max_depth}, "
        f"single rotor: {cfg.n_blades_per_rotor} blades",
        fontsize=12,
        fontweight="bold",
    )

    gs = fig.add_gridspec(3, 2, height_ratios=[1.1, 1.0, 0.9], hspace=0.38, wspace=0.28)

    ax = fig.add_subplot(gs[0, 0])
    im = ax.pcolormesh(ts_std * 1e3, f_std, s_std, shading="auto", cmap="turbo", vmin=-55, vmax=0)
    ax.set_title("Standard Doppler from RT snapshots")
    ax.set_xlabel("Time [ms]")
    ax.set_ylabel("Doppler frequency [Hz]")
    ax.set_ylim(-cfg.nyquist, cfg.nyquist)
    fig.colorbar(im, ax=ax, label="Normalised power [dB]")

    ax = fig.add_subplot(gs[0, 1])
    im = ax.pcolormesh(ts_micro * 1e3, f_micro, s_micro, shading="auto", cmap="turbo", vmin=-55, vmax=0)
    ax.set_title("Single-rotor micro-Doppler from RT-updated blade scatterers")
    ax.set_xlabel("Time [ms]")
    ax.set_ylabel("Doppler frequency [Hz]")
    ax.set_ylim(-cfg.nyquist, cfg.nyquist)
    fig.colorbar(im, ax=ax, label="Normalised power [dB]")

    ax = fig.add_subplot(gs[1, 0])
    ax.plot(t * 1e3, fi_std, color="#1f77b4", linewidth=1.0)
    ax.axhline(
        np.median(fi_std),
        color="black",
        linestyle="--",
        linewidth=0.8,
        label=f"median={np.median(fi_std):+.1f} Hz",
    )
    ax.set_title("Standard Doppler instantaneous frequency")
    ax.set_xlabel("Time [ms]")
    ax.set_ylabel("Frequency [Hz]")
    ax.grid(True, alpha=0.3)
    ax.legend(loc="best")

    ax = fig.add_subplot(gs[1, 1])
    ax.plot(t * 1e3, fi_micro, color="#d62728", linewidth=1.0)
    ax.axhline(
        np.median(fi_micro),
        color="black",
        linestyle="--",
        linewidth=0.8,
        label=f"median={np.median(fi_micro):+.1f} Hz",
    )
    ax.set_title("Single-rotor micro-Doppler instantaneous frequency")
    ax.set_xlabel("Time [ms]")
    ax.set_ylabel("Frequency [Hz]")
    ax.grid(True, alpha=0.3)
    ax.legend(loc="best")

    ax = fig.add_subplot(gs[2, 0])
    pos = standard["positions"]
    ax.plot(pos[:, 0], pos[:, 1], color="#1f77b4", linewidth=1.5)
    ax.scatter([cfg.radar_position[0]], [cfg.radar_position[1]], marker="^", color="green", label="radar")
    ax.scatter([pos[0, 0]], [pos[0, 1]], marker="o", color="black", label="start")
    ax.set_title("RT standard case: linear target trajectory")
    ax.set_xlabel("x [m]")
    ax.set_ylabel("y [m]")
    ax.axis("equal")
    ax.grid(True, alpha=0.3)
    ax.legend(loc="best")

    ax = fig.add_subplot(gs[2, 1])
    blade = micro["first_blade_positions"]
    rotor_center = micro["rotor_center_positions"]
    body = micro["body_positions"]
    ax.plot(blade[:, 0], blade[:, 1], color="#d62728", linewidth=1.2, label="one blade-tip RT trajectory")
    ax.scatter([rotor_center[0, 0]], [rotor_center[0, 1]], marker="+", color="purple", label="single rotor center")
    ax.scatter([body[0, 0]], [body[0, 1]], marker="x", color="black", label="body center")
    ax.scatter([cfg.radar_position[0]], [cfg.radar_position[1]], marker="^", color="green", label="radar")
    ax.set_title("RT micro case: single-rotor blade-tip trajectory")
    ax.set_xlabel("x [m]")
    ax.set_ylabel("y [m]")
    ax.axis("equal")
    ax.grid(True, alpha=0.3)
    ax.legend(loc="best")

    fig.text(
        0.5,
        0.01,
        "Signal source: Sionna RT CIR at every snapshot. "
        "No MicroDopplerModulator signal generator is used. "
        "Micro case: one body point + one rotor with blade-tip point scatterers.",
        ha="center",
        fontsize=9,
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_path, dpi=200, bbox_inches="tight")
    print(f"\nSaved figure: {output_path}")


def main() -> None:
    args = parse_args()
    cfg = RtCaseConfig(
        carrier_freq=args.fc,
        fs_snapshot=args.fs,
        n_snapshots=args.snapshots,
        standard_speed=args.standard_speed,
        blade_radius=args.blade_radius,
        rotation_freq=args.rotation_freq,
        n_blades_per_rotor=max(1, args.n_blades),
        rotor_offset=(args.rotor_offset_x, args.rotor_offset_y, args.rotor_offset_z),
        rotor_initial_phase=args.rotor_phase,
        body_weight=args.body_weight,
        blade_weight=args.blade_weight,
        max_depth=args.max_depth,
        diffuse_reflection=args.diffuse,
    )

    print("=" * 72)
    print("  RT-generated single-rotor micro-Doppler vs standard Doppler")
    print("=" * 72)
    print(f"  scene            : {args.scene}")
    print(f"  output           : {args.output}")
    print(f"  fc               : {cfg.carrier_freq/1e9:.1f} GHz")
    print(f"  lambda           : {cfg.wavelength*1e3:.2f} mm")
    print(f"  snapshots        : {cfg.n_snapshots} @ {cfg.fs_snapshot:.0f} Hz")
    print(f"  Nyquist          : ±{cfg.nyquist:.1f} Hz")
    print(f"  standard v       : {cfg.standard_speed:.2f} m/s")
    print(f"  single rotor     : {cfg.n_blades_per_rotor} blades")
    print(f"  blade R/frot     : {cfg.blade_radius:.3f} m / {cfg.rotation_freq:.1f} Hz")
    print(f"  rotor offset     : {cfg.rotor_offset}")
    print(f"  weights          : body={cfg.body_weight:.3f}, blade={cfg.blade_weight:.3f}")
    print(f"  one-way beta     : {cfg.one_way_beta_max:.2f} rad")
    print(f"  one-way peak mD  : ±{cfg.one_way_peak_micro_doppler:.1f} Hz")
    print(f"  RT depth         : {cfg.max_depth}, diffuse={cfg.diffuse_reflection}")

    if cfg.one_way_peak_micro_doppler > 0.8 * cfg.nyquist:
        print("\n  WARNING: estimated one-way micro-Doppler is close to snapshot Nyquist.")
        print("           Increase --fs or reduce --blade-radius / --rotation-freq to avoid aliasing.\n")

    standard = simulate_standard_rt(args.scene, cfg)
    micro = simulate_micro_rt(args.scene, cfg)
    plot_results(standard, micro, cfg, args.scene, Path(args.output))


if __name__ == "__main__":
    main()